# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# tt.py
# Created on: 2015-01-04 16:47:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
facilities = "facilities"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(facilities, "NEW_SELECTION", "\"ID\" = 0")

