# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# tt.py
# Created on: 2015-04-01 16:09:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Arcs = "Arcs"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Arcs, "NEW_SELECTION", "\"OBJECTID\" = 1")

